# Generated by Django 4.1.4 on 2022-12-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_url_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='unique_id',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
