# Generated by Django 4.1.4 on 2023-01-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_url_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicks',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
